import { StyleSheet } from 'react-native';

// Enhanced colors for Login
const colors = {
  primary: '#4F46E5',
  secondary: '#3730A3',
  backgroundSolid: '#F8FAFC',
  white: '#FFFFFF',
  error: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  border: '#E2E8F0',
  text: {
    primary: '#1E293B',
    secondary: '#64748B',
    placeholder: '#94A3B8',
    disabled: '#CBD5E1',
    light: '#64748B',
  },
  auth: {
    primary: '#4F46E5',
    secondary: '#3730A3',
    background: '#F8FAFC',
    border: '#E2E8F0',
    inputBackground: '#FFFFFF',
    gradient: ['#4F46E5', '#3730A3'],
    accent: '#8B5CF6',
    glow: 'rgba(79, 70, 229, 0.3)',
  }
};

// Enhanced shadows for Login
const shadows = {
  small: {
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  medium: {
    elevation: 6,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  large: {
    elevation: 12,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  premium: {
    elevation: 16,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  glow: {
    elevation: 20,
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
  },
};

export const LoginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundSolid,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 56,
    position: 'relative',
  },
  logo: {
    width: 140,
    height: 140,
    marginBottom: 24,
    borderRadius: 70,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.glow,
    borderWidth: 4,
    borderColor: 'rgba(79, 70, 229, 0.1)',
  },
  logoGlow: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: colors.auth.glow,
    top: -10,
    opacity: 0.6,
  },
  appName: {
    fontSize: 48,
    fontWeight: '900',
    color: colors.auth.primary,
    marginBottom: 12,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(79, 70, 229, 0.3)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
  },
  appSlogan: {
    fontSize: 20,
    color: colors.text.secondary,
    textAlign: 'center',
    maxWidth: '85%',
    fontWeight: '600',
    letterSpacing: 0.5,
    lineHeight: 28,
  },
  formContainer: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
  },
  inputContainer: {
    marginBottom: 20,
    position: 'relative',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.auth.border,
    height: 64,
    paddingHorizontal: 24,
    ...shadows.medium,
    position: 'relative',
    overflow: 'hidden',
  },
  inputWrapperFocused: {
    borderColor: colors.auth.primary,
    backgroundColor: colors.white,
    ...shadows.premium,
    transform: [{ scale: 1.02 }],
  },
  inputGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: colors.auth.primary,
    opacity: 0,
  },
  inputGlowActive: {
    opacity: 1,
  },
  input: {
    flex: 1,
    fontSize: 18,
    color: colors.text.primary,
    height: '100%',
    padding: 0,
    marginLeft: 16,
    fontWeight: '600',
  },
  inputIcon: {
    color: colors.text.secondary,
  },
  passwordToggle: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.auth.background,
    marginLeft: 8,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    marginTop: 16,
    marginBottom: 24,
    padding: 12,
    borderRadius: 12,
  },
  forgotPasswordText: {
    color: colors.auth.primary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  loginButton: {
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.auth.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    ...shadows.premium,
    position: 'relative',
    overflow: 'hidden',
  },
  loginButtonGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
  },
  loginButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  loginButtonDisabled: {
    backgroundColor: colors.text.disabled,
    ...shadows.small,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 2,
    backgroundColor: colors.auth.border,
    borderRadius: 1,
  },
  dividerText: {
    color: colors.text.light,
    paddingHorizontal: 20,
    fontSize: 16,
    fontWeight: '600',
    backgroundColor: colors.backgroundSolid,
  },
  socialButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 24,
  },
  socialButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 16,
    borderWidth: 2,
    borderColor: colors.auth.border,
    ...shadows.medium,
  },
  socialButtonActive: {
    borderColor: colors.auth.primary,
    ...shadows.premium,
  },
  registerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
    backgroundColor: colors.white,
    borderRadius: 20,
    marginTop: 16,
    ...shadows.medium,
    borderWidth: 1,
    borderColor: colors.auth.border,
  },
  registerText: {
    color: colors.text.secondary,
    fontSize: 16,
    fontWeight: '600',
  },
  registerButton: {
    marginLeft: 8,
    padding: 8,
    borderRadius: 8,
  },
  registerButtonText: {
    color: colors.auth.primary,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  loadingOverlay: {
    backgroundColor: 'rgba(79, 70, 229, 0.1)',
    borderRadius: 16,
    padding: 20,
  },
  // Floating elements
  floatingElement: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(79, 70, 229, 0.05)',
    top: 100,
    right: -50,
  },
  floatingElement2: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(139, 92, 246, 0.05)',
    bottom: 200,
    left: -75,
  },
  // Animation states
  inputFocused: {
    transform: [{ scale: 1.02 }],
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  // Enhanced visual effects
  glowEffect: {
    shadowColor: colors.auth.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 20,
  },
});

export { colors };