import { StyleSheet } from 'react-native';

// Enhanced colors for Register
const colors = {
  primary: '#7C3AED',
  secondary: '#5B21B6',
  backgroundSolid: '#F8FAFC',
  white: '#FFFFFF',
  error: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  border: '#E2E8F0',
  text: {
    primary: '#1E293B',
    secondary: '#64748B',
    placeholder: '#94A3B8',
    disabled: '#CBD5E1',
    light: '#64748B',
  },
  auth: {
    primary: '#7C3AED',
    secondary: '#5B21B6',
    background: '#F8FAFC',
    border: '#E2E8F0',
    inputBackground: '#FFFFFF',
    gradient: ['#7C3AED', '#5B21B6'],
    accent: '#A855F7',
    glow: 'rgba(124, 58, 237, 0.3)',
  }
};

// Enhanced shadows for Register
const shadows = {
  small: {
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  medium: {
    elevation: 6,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  large: {
    elevation: 12,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  premium: {
    elevation: 16,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  glow: {
    elevation: 20,
    shadowColor: '#A855F7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
  },
};

export const RegisterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundSolid,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  content: {
    flex: 1,
    paddingBottom: 32,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  headerGlow: {
    position: 'absolute',
    width: 200,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.auth.glow,
    top: -20,
    opacity: 0.3,
  },
  title: {
    fontSize: 44,
    fontWeight: '900',
    color: colors.auth.primary,
    marginBottom: 12,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(124, 58, 237, 0.3)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
  },
  subtitle: {
    fontSize: 20,
    color: colors.text.secondary,
    textAlign: 'center',
    maxWidth: '90%',
    fontWeight: '600',
    letterSpacing: 0.5,
    lineHeight: 28,
  },
  formContainer: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
  },
  inputContainer: {
    marginBottom: 20,
    position: 'relative',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.auth.border,
    height: 64,
    paddingHorizontal: 24,
    ...shadows.medium,
    position: 'relative',
    overflow: 'hidden',
  },
  inputWrapperFocused: {
    borderColor: colors.auth.primary,
    backgroundColor: colors.white,
    ...shadows.premium,
    transform: [{ scale: 1.02 }],
  },
  inputGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: colors.auth.primary,
    opacity: 0,
  },
  inputGlowActive: {
    opacity: 1,
  },
  input: {
    fontSize: 18,
    color: colors.text.primary,
    height: 64,
    fontWeight: '600',
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingHorizontal: 24,
    borderWidth: 2,
    borderColor: colors.auth.border,
    ...shadows.medium,
  },
  inputIcon: {
    color: colors.text.secondary,
    marginRight: 16,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.auth.border,
    height: 64,
    paddingHorizontal: 24,
    ...shadows.medium,
    position: 'relative',
    overflow: 'hidden',
  },
  passwordContainerFocused: {
    borderColor: colors.auth.primary,
    ...shadows.premium,
    transform: [{ scale: 1.02 }],
  },
  passwordInput: {
    flex: 1,
    fontSize: 18,
    color: colors.text.primary,
    height: '100%',
    padding: 0,
    fontWeight: '600',
  },
  eyeIcon: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.auth.background,
    marginLeft: 8,
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    marginTop: 8,
    marginLeft: 8,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  registerButton: {
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.auth.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 20,
    ...shadows.premium,
    position: 'relative',
    overflow: 'hidden',
  },
  registerButtonGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
  },
  registerButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  registerButtonDisabled: {
    backgroundColor: colors.text.disabled,
    ...shadows.small,
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 8,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    ...shadows.medium,
    borderWidth: 1,
    borderColor: colors.auth.border,
  },
  termsCheckbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.auth.primary,
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    ...shadows.small,
  },
  termsCheckboxChecked: {
    backgroundColor: colors.auth.primary,
    ...shadows.medium,
  },
  termsText: {
    flex: 1,
    fontSize: 15,
    color: colors.text.secondary,
    fontWeight: '600',
    lineHeight: 22,
  },
  termsLink: {
    color: colors.auth.primary,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
    backgroundColor: colors.white,
    borderRadius: 20,
    marginTop: 16,
    ...shadows.medium,
    borderWidth: 1,
    borderColor: colors.auth.border,
  },
  loginText: {
    color: colors.text.secondary,
    fontSize: 16,
    fontWeight: '600',
  },
  loginLink: {
    marginLeft: 8,
    padding: 8,
    borderRadius: 8,
  },
  loginLinkText: {
    color: colors.auth.primary,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  loadingOverlay: {
    backgroundColor: 'rgba(124, 58, 237, 0.1)',
    borderRadius: 16,
    padding: 20,
  },
  // Progress indicator
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  progressStep: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.auth.border,
    marginHorizontal: 4,
  },
  progressStepActive: {
    backgroundColor: colors.auth.primary,
    width: 32,
    borderRadius: 6,
  },
  // Floating elements
  floatingElement: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(124, 58, 237, 0.05)',
    top: 80,
    right: -60,
  },
  floatingElement2: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(168, 85, 247, 0.05)',
    bottom: 150,
    left: -90,
  },
  // Animation states
  inputFocused: {
    transform: [{ scale: 1.02 }],
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  // Enhanced visual effects
  glowEffect: {
    shadowColor: colors.auth.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 20,
  },
  // Strength indicator
  strengthIndicator: {
    height: 4,
    backgroundColor: colors.auth.border,
    borderRadius: 2,
    marginTop: 8,
    overflow: 'hidden',
  },
  strengthFill: {
    height: '100%',
    borderRadius: 2,
  },
  strengthWeak: {
    backgroundColor: colors.error,
    width: '33%',
  },
  strengthMedium: {
    backgroundColor: colors.warning,
    width: '66%',
  },
  strengthStrong: {
    backgroundColor: colors.success,
    width: '100%',
  },
  // Success animation
  successContainer: {
    alignItems: 'center',
    padding: 40,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.success,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    ...shadows.glow,
  },
  successText: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.success,
    textAlign: 'center',
    marginBottom: 12,
  },
  successSubText: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center',
    fontWeight: '500',
  },
});

export { colors };